apiVersion: v1
kind: Service
metadata:
  name: procurement-api
  namespace: procurement-ns-1
spec:
  type: LoadBalancer
  selector: { app: procurement-backend }
  ports: [{ port: 8000, targetPort: 8000, nodePort: 30002 }]