apiVersion: v1
kind: Service
metadata:
  name: procurement-frontend
  namespace: procurement-ns-1
spec:
  type: LoadBalancer
  selector:
    app: procurement-frontend
  ports:
    - name: http
      appProtocol: http
      port: 3100
      targetPort: 3000