"""Deterministic comparison for immutable purchase-order snapshots."""

from __future__ import annotations

from collections import defaultdict
from typing import Any

from ..models import OrderVersion
from ..schemas import VersionChange, VersionDiffResponse
from .orders import version_response


def _path(prefix: str, segment: str) -> str:
    return f"{prefix}.{segment}" if prefix else segment


def _line_item_key(item: dict[str, Any]) -> str:
    """Stable matching key; line_number is generated by ingestion and not durable."""
    description = " ".join(str(item.get("description") or "").casefold().split())
    size = " ".join(str(item.get("size") or "").casefold().split())
    return f"{description}|{size}"


def _index_line_items(items: list[dict[str, Any]]) -> dict[str, dict[str, Any]]:
    indexed: dict[str, dict[str, Any]] = {}
    duplicates: defaultdict[str, int] = defaultdict(int)
    for item in items:
        key = _line_item_key(item)
        duplicates[key] += 1
        indexed[f"{key}#{duplicates[key]}"] = item
    return indexed


def _diff_values(before: Any, after: Any, path: str, changes: list[VersionChange]) -> None:
    if isinstance(before, dict) and isinstance(after, dict):
        for key in sorted(set(before) | set(after)):
            _diff_values(before.get(key), after.get(key), _path(path, str(key)), changes)
        return
    if isinstance(before, list) and isinstance(after, list):
        if all(isinstance(item, dict) and "description" in item for item in [*before, *after]):
            before_by_item = _index_line_items(before)
            after_by_item = _index_line_items(after)
            for key in sorted(set(before_by_item) | set(after_by_item)):
                before_item = before_by_item.get(key)
                after_item = after_by_item.get(key)
                label = (after_item or before_item or {}).get("description", "Unknown item")
                item_path = f"line_items[{label}]"
                if before_item is None:
                    changes.append(VersionChange(path=f"{item_path}.status", before="Not present", after="Added"))
                    continue
                if after_item is None:
                    changes.append(VersionChange(path=f"{item_path}.status", before="Present", after="Removed"))
                    continue
                clean_before = {name: value for name, value in before_item.items() if name != "line_number"}
                clean_after = {name: value for name, value in after_item.items() if name != "line_number"}
                _diff_values(clean_before, clean_after, item_path, changes)
            return
    if before != after:
        changes.append(VersionChange(path=path, before=before, after=after))


def version_diff(base: OrderVersion, target: OrderVersion) -> VersionDiffResponse:
    excluded = {"id", "version_number", "source_type", "created_by_type", "created_at"}
    before = version_response(base).model_dump(mode="json", exclude=excluded)
    after = version_response(target).model_dump(mode="json", exclude=excluded)
    changes: list[VersionChange] = []
    _diff_values(before, after, "", changes)
    return VersionDiffResponse(base_version_id=base.id, version_id=target.id, changes=changes)